pipeline {
  agent { 
    node {
      label 'docker-arch-builder'
    }
  }
  triggers {
    pollSCM '*/2 * * * *'
  }
  stages {
    stage('build') {
      steps {
        echo "Building sample app..."
        sh '''
        mkdir -p build
        cd build
        export CC=/usr/bin/clang && export CXX=/usr/bin/clang++ && cmake ..
        export CC=/usr/bin/clang && export CXX=/usr/bin/clang++ && cmake --build . --config Debug --target ALL_BUILD
        '''
        echo "Build completed."
      }
    }
    // TODO: add tests
    stage('deliver') {
      steps {
        echo 'Delivering built sample app...'
        sh '''
        echo "TODO: implement delivery"
        '''
      }
    }
  }
}