pipeline {
  agent { 
    node {
      label 'docker-arch-builder'
    }
  }
  triggers {
    pollSCM '*/2 * * * *'
  }
  stages {
    stage('build') {
      environment {
        CC = '/usr/bin/clang'
        CXX = '/usr/bin/clang++'
      }
      steps {
        echo "Building sample app..."
        sh '''
        mkdir -p build
        cd build
        cmake -G Ninja ..
        cmake --build . --config Debug --target ALL_BUILD
        '''
        echo "Build completed."
      }
    }
    // TODO: add tests
    stage('deliver') {
      steps {
        echo 'Delivering built sample app...'
        sh '''
        echo "TODO: implement delivery"
        '''
      }
    }
  }
}